title: Aiming Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
source: src
destination: dist
permalink: "/:categories/:title"

description: "çŸ­è…¿çš„å‰è¶³çƒğŸ¶"
url: "https://MaYiFei1995.github.io"

description: Aimingçš„åšå®¢ | Aiming Blog
