# Site settings
title: Aiming Blog
SEOTitle: Aimingçš„åšå®¢ | Aiming Blog
email: maxiaochou1030@gmail.com
description: "çŸ­è…¿çš„å‰è¶³çƒğŸ¶"
url: "https://MaYiFei1995.github.io"
theme: jekyll-theme-architect

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     38åˆ†
