email: maxiaochou1030@gmail.com
description: "çŸ­è…¿çš„å‰è¶³çƒğŸ¶"
url: "https://MaYiFei1995.github.io"

# SNS settings
RSS: false
weibo_username:     38åˆ†

permalink: /:year:month:day/:title
url: #Your url here
baseurl: /project

# variables
name: Aiming Blog
description: Aimingçš„åšå®¢ | Aiming Blog
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true